blank_issues_enabled: false
contact_links:
  - name: SpigotMC Thread
    url: https://www.spigotmc.org/threads/mobchip-entity-ai-wrapper-pathfinders-controllers-and-more.556441/
    about: Read about MobChip!
