name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    name: Gradle Setup
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Setup Project
        run: ./gradlew project tasks :mobchip-bukkit:dependencies

  build:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 10

    name: Build Java 21
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean assemble publishToMavenLocal

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: setup

    name: Test Project
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Test
        run: ./gradlew test

  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [test, build]

    name: Create Artifacts
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mobchip
          path: |
            bukkit/build/libs/*.jar
            base/build/libs/*.jar
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: mobchip-test-reports
          path: '**/jacocoHtml/'


  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy JavaDocs
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Build JavaDocs
        run: ./gradlew clean allJavadoc
      - name: Deploy JavaDoc
        run: bash javadoc.sh ${GITHUB_SHA::7}
